### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by TonyBirt** [jmriego/emulation#2]
C:\Launchbox2AEL>launchbox2ael.py
Traceback (most recent call last):
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Launchbox2AEL\LaunchBox2AEL.py", line 86, in <module>
    categories, launchers = generate_data()
  File "C:\Launchbox2AEL\LaunchBox2AEL.py", line 28, in generate_data
    launchers = AELLaunchersCatalog(launchbox.games, DOSBOX_EXE, DOSBOX_ARGS)
  File "C:\Launchbox2AEL\launchbox\catalog.py", line 65, in games
    self.resources)
  File "C:\Launchbox2AEL\launchbox\game.py", line 49, in __init__
    games_xml = untangle.parse(File([platforms_xml_dir, '{}.xml'.format(platform.name)]).absolute)
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\site-packages\untangle.py", line 182, in parse
    parser.parse(StringIO(filename))
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\Users\BirtLaden.DESKTOP-SAU1DGS\AppData\Local\Programs\Python\Python37\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:2: not well-formed (invalid token)

**Comment by TonyBirt** [comment]
Hi Mysticalp, I messaged you in the AEL forum thread, thank you for you reply there.  I am a beginner in Python sorry.

**Comment by jmriego** [comment]
Hi! Yes, I took a long time to see that message. I don't get notifications of messages but I always look at github. Don't worry. Let's try to get this sorted.
Just to be sure, did you install the library required? `pip install lxml` or maybe `pip3 install lxml` if you have both Python 2 and 3 installed in your computer.

I have added some text so we can see which platform games is the script having problems with. Can you try downloading this again and running it so I have a better idea of what's happening?

**Comment by BirtLaden** [comment]
Hi, thanks for the reply :)  It is giving me a different error now.
C:\Launchbox2AEL>launchbox2ael.py
Traceback (most recent call last):
  File "C:\Launchbox2AEL\LaunchBox2AEL.py", line 87, in <module>
    write_files(categories, launchers)
  File "C:\Launchbox2AEL\LaunchBox2AEL.py", line 69, in write_files
    tree.write(f_rom_base_noext, pretty_print=True)
  File "src\lxml\etree.pyx", line 2048, in lxml.etree._ElementTree.write
  File "src\lxml\serializer.pxi", line 721, in lxml.etree._tofilelike
  File "src\lxml\serializer.pxi", line 780, in lxml.etree._create_output_buffer
  File "src\lxml\serializer.pxi", line 770, in lxml.etree._create_output_buffer
FileNotFoundError: [Errno 2] No such file or directory

**Comment by jmriego** [comment]
No worries!

I think you almost got it. What do you have in the config.ini file?
It's not finding AEL in the folder it's pointing to in the configuration
file
