### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by drafttoshape** [jmriego/emulation#3]
Hello,

First thanks for your code. But it's not working on my machine. Any idee?

please have a look: 

F:\Launchbox\Export to AEL>LaunchBox2AEL.py
Generating list of Windows games
Generating list of Super Nintendo Entertainment System games
Traceback (most recent call last):
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Launchbox\Export to AEL\LaunchBox2AEL.py", line 86, in <module>
    categories, launchers = generate_data()
  File "F:\Launchbox\Export to AEL\LaunchBox2AEL.py", line 28, in generate_data
    launchers = AELLaunchersCatalog(launchbox.games, DOSBOX_EXE, DOSBOX_ARGS)
  File "F:\Launchbox\Export to AEL\launchbox\catalog.py", line 65, in games
    self.resources)
  File "F:\Launchbox\Export to AEL\launchbox\game.py", line 50, in __init__
    games_xml = untangle.parse(File([platforms_xml_dir, '{}.xml'.format(platform.name)]).absolute)
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\site-packages\untangle.py", line 182, in parse
    parser.parse(StringIO(filename))
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\Users\macsauce\AppData\Local\Programs\Python\Python37-32\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:2: not well-formed (invalid token)

**Comment by jmriego** [comment]
no worries! always good to see more people using it

I'm afraid the issue is directly on the untangle library for Python.

The step that is failing is the `untangle.parse` of the xml file. Which is a library that reads XML files. Let's try to figure out if there is any issue with the XML file.

Could you try to run this command in Python?
`games_xml = untangle.parse(r'C:\LaunchBox\Data\Platforms\Super Nintendo Entertainment System.xml')`

That's supposing LaunchBox is in that folder, just change that to the appropriate one
